### ISSUE TITLE
Output from `bundle install` command

### ISSUE THREAD

**Issue by drnic** [paketo-buildpacks/bundle-install#104]
Currently the `building` stage output does not include the output from running `bundle install`:

```
Paketo Bundle Install Buildpack 0.0.60
  Executing build process
    Running 'bundle config path /layers/paketo-buildpacks_bundle-install/gems'
    Running 'bundle config cache_path --parseable'
    Running 'bundle install'
      Completed in 20.239s
```

Could we get this output included please to show progress?

**Comment by sophiewigmore** [comment]
Hi @drnic,
I would like to clarify, are you looking for the actual `bundle install` output in the logs or do you mean you would like some type of logs just to show the progress of the command?

**Comment by drnic** [comment]
@sophiewigmore correct, the first one: the normal `bundle install` output.

Since creating this ticket I'm aware that when `bundle install` fails then the output is printed to the screen; which is good. Maybe this is sufficient. I'm open to other's opinions of what they expect: a) as a Ruby user who is using the buildpacks for the first time; b) regular buildpack user (who might want a quieter screen with less output)

**Comment by sophiewigmore** [comment]
@drnic cool, that makes sense. Our current mantra is to keep the logs streamlined and uncluttered when things pass as expected. However, I agree with you that it could be be useful to provide more detailed log output if a user needs it. There are a few options I'd be interested in exploring eventually to add optional verbose buildpack logs, but none of them are quick changes as this would be something we'd want to be consistent across many buildpacks. 

For now the logs will stay the same, but I  will keep you posted if this if something we decide to go through with in the future

**Comment by genevieve** [comment]
This is sort of related, but we would also like to see more verbose output for the commands that the buildpack runs. Even if the command does not fail, for debugging purposes, it is helpful to see _exactly_ what happened when a failure doesn't occur but some behavior appears incorrect as result. For example, it would be great if there was a `BP_LOG_LEVEL=verbose` so that we could see the output of the rails-asset buildpack command. For instance, if that var is present, we would run:
```
bundle exec rails --trace assets:precompile assets:clean
```
with the `--trace` flag in addition.

**Comment by sophiewigmore** [comment]
I've been thinking about something like this for a while now. I think it could be really useful, it's good to have user feedback from you and @drnic about the need to for this. I'll keep you in the loop!

**Comment by sophiewigmore** [comment]
Related issue in progress: https://github.com/paketo-buildpacks/packit/issues/252

**Comment by sophiewigmore** [comment]
Related: https://github.com/paketo-buildpacks/packit/pull/280

**Comment by sophiewigmore** [comment]
Hey! It's been a while but I wanted to point out that [v0.4.0 of this buildpack](https://github.com/paketo-buildpacks/bundle-install/releases/tag/v0.4.0) now includes both log output from the `bundle install` command, as well as support for a `BP_LOG_LEVEL=DEBUG` environment variable setting for insight into the build commands. We're in the process of rolling out this type of logging to all of the buildpacks in the Ruby language family, but it's complete in Bundle Install as of now!

**Comment by hidde-jan** [comment]
@sophiewigmore is it possible to override the version of a "sub" buildpack (e.g. bundle-install@0.4.0). The current ruby buildpack (0.11.0 I think) uses version 0.3.1.

Adding `--buildpack paketo-buildpacks/bundle-install@0.4.0` does not work and I can't find any documentation on the paketo site.

**Comment by ryanmoran** [comment]
There is not a way to override just a single buildpack within the order grouping of a metabuildpack. Instead, you can recreate the group with the updated version. For example, to recreate this group: https://github.com/paketo-buildpacks/ruby/blob/v0.11.0/buildpack.toml#L249-L305

You can update `bundle-install` here with something like the following

```
pack build rack-app \
  --buildpack paketo-buildpacks/mri@0.6.0 \
  --buildpack paketo-buildpacks/bundler@0.3.1 \
  --buildpack paketo-buildpacks/bundle-install@0.4.0 \
  --buildpack paketo-buildpacks/rackup@0.2.1
```

**Comment by sophiewigmore** [comment]
@drnic closing this out since I think it's been addressed. Feel free to re-open if needed!
