### ISSUE TITLE
bundle-install fails to install the mysql2 gem

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/bundle-install#121]
## What happened?

Please provide some details about the task you are trying to accomplish and
what went wrong.

* What were you attempting to do?

Build a ruby application that has the mysql2 gem specified in it's Gemfile.

This worked after building a new stack build image _on top of_ the CNB Full Stack build image and running `apt-get install libmysqlclient-dev`.

* What did you expect to happen?

The image to successfully build.

It looks like there's a variant of the libmariadb-dev library but it doesn't seem to meet the requirements for the mysql2 gem: https://github.com/paketo-buildpacks/stacks/blob/caf3e44bd54c3a8cc4da0dafe65d3d875142a908/packages/full/build#L89-L90

* What was the actual behavior? Please provide log output, if possible.

```
Installing mysql2 0.5.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/layers/paketo-buildpacks_bundle-install/gems/ruby/2.5.0/gems/mysql2-0.5.3/ext/mysql2
/layers/paketo-buildpacks_mri/mri/bin/ruby -r ./siteconf20201203-76-wo6d1g.rb
extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
checking for -lmysqlclient... no
-----
mysql client is missing. You may need to 'sudo apt-get install libmariadb-dev',
'sudo apt-get install libmysqlclient-dev' or 'sudo yum install mysql-devel', and
try again.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

## Build Configuration

Please provide some details about your build configuration.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.

- Latest CNB Full Stack 
- pack cli version 0.14.1

* What buildpacks are you using? Please include versions.

```
===> DETECTING
======== Results ========
pass: paketo-buildpacks/mri@0.0.164
pass: paketo-buildpacks/bundler@0.0.153
pass: paketo-buildpacks/bundle-install@0.0.60
pass: paketo-buildpacks/puma@0.0.52
pass: paketo-buildpacks/procfile@2.0.3
```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

A custom builder with the paketo-buildpacks ruby buildpack specified.

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

We don't need a `buildpack.yml` for this app, and the Gemfile contains:
```
...
  gem "mysql2"
...
```

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by martyspiewak** [comment]
Hi @genevieve. I'm having trouble reproducing this issue.

I tried to use the [sample app](https://github.com/paketo-buildpacks/bundle-install/tree/main/integration/testdata/simple_app) and add `gem "mysql2"` to the Gemfile, but I was able to successfully run `pack build test-app -B paketobuildpacks/builder:full` after doing this.

Could you please provide more info about your app to help me reproduce?

**Comment by genevieve** [comment]
Hey @martyspiewak! I actually can't seem to reproduce it after removing the `libmysqlclient-dev` library and going back to the plain CNB full stack. If it happens again, I'll post more details to reproduce. Thanks!
