### ISSUE TITLE
Pack always assume production image is being built

### ISSUE THREAD

**Issue by jwhitcraft** [paketo-buildpacks/bundle-install#255]
## What happened?
Trying to build an container for ci test runs, and the development/test gems are missing

* What were you attempting to do?
I'm trying to build a image to use in multiple different CI runs, thus the `development:test` gems are need in the launch layer.

* What did you expect to happen?
A way to the launch layer to be configured to allow development and test gems to be included

* What was the actual behavior? Please provide log output, if possible.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

pack: 0.21.1

* What buildpacks are you using? Please include versions.

paketo-buildpacks/ca-certificates 2.4.0
paketo-buildpacks/mri             0.2.5
paketo-buildpacks/bundler         0.1.9
paketo-buildpacks/bundle-install  0.2.4
paketo-buildpacks/node-engine     0.7.1
paketo-buildpacks/yarn            0.4.0
paketo-buildpacks/yarn-install    0.4.0
paketo-buildpacks/rails-assets    0.2.4
paketo-buildpacks/puma            0.0.61
paketo-buildpacks/procfile        4.3.0

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

paketobuildpacks/builder:full

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by sophiewigmore** [comment]
@jwhitcraft It seems reasonable to me that we would allow a user to overwrite the value as you described. As Arjun noted we tend to generate production images, but as far as I know this isn't a strict rule. @arjun024 / @ryanmoran do either of you see an issue with this?

**Comment by fg-j** [comment]
@jwhitcraft and @paketo-buildpacks/ruby-maintainers This issue hasn't had activity in a while. Is this still a problem? Is there a workaround?

**Comment by sophiewigmore** [comment]
@jwhitcraft Hi, I'm wondering if you ever tried created a configuration file in your app? I think you can override this behaviour by setting bundler configuration inside a `.bundle/config` file inside of your application, and then setting the following inside:
```
---
BUNDLE_WITHOUT: ""

```
