### ISSUE TITLE
The buildpack should error if the Gemfile and Gemfile.lock are out of sync.

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/bundle-install#93]
I updated the puma gem in my `Gemfile` but didn't update the `Gemfile.lock` and the buildpack reused the cache without erroring:
```
Paketo Bundle Install Buildpack 0.0.59
  Reusing cached layer /layers/paketo-buildpacks_bundle-install/gems
```

I expect that it either:
- Errors because the Gemfile.lock is out of sync; or
- Rebuilds the layer

**Comment by arjun024** [comment]
Steps to reproduce issue

1. Checkout [this app](https://github.com/paketo-buildpacks/puma/tree/v0.0.53/integration/testdata/sinatra_app).

1. Change one line of `Gemfile` from `gem 'puma'` to `gem 'puma', '~> 5.0.2'`.

1. `pack build mypuma -b gcr.io/paketo-buildpacks/ruby`

1. Build succeeds and `docker run -it -p 9292:9292 mypuma` succeeds.

1. Now change the same line of `Gemfile` to `gem 'puma', '~> 5.0.4'`

1. `pack build mypuma -b gcr.io/paketo-buildpacks/ruby`

1. You can see that build succeeds by reusing the layer:
```
[builder] Paketo Bundle Install Buildpack 0.1.0                                                                                                                                          │···
[builder]   Reusing cached layer /layers/paketo-buildpacks_bundle-install/gems
```
Instead, the build should fail with a reasonable error message.

**Comment by sophiewigmore** [comment]
Hey @genevieve, we have just released [bundle-install v0.1.1](https://github.com/paketo-buildpacks/bundle-install/releases/tag/v0.1.1), which contains changes that should address this issue. Would you be able to check it out some time and verify that this feature now works as you were expecting?

**Comment by genevieve** [comment]
Hey @sophiewigmore. This is working as expected. We use the `vendor/cache` so when we change the Gemfile without running `bundle install` locally, the buildpack fails to run `bundle install --local`.

**Comment by sophiewigmore** [comment]
@genevieve it fails? Is that expected? I would've expected if you changed a gem without running `bundle install` that on the rebuild the buildpack would rebuild the layer with `bundle install --local`

**Comment by genevieve** [comment]
The buildpack is trying to rebuild the layer because the Gemfiles are out of sync but it's failing because it tries to rebuild the layer the same way (with `bundle install --local`). This won't work because the gem wasn't downloaded from the repository to the local cache and so it's correct behavior that it fails. The first part that needed addressing was the cache layer reuse when Gemfile/.lock was out of sync leads to a helpful error for users.

**Comment by sophiewigmore** [comment]
@genevieve Ah, I understand what you mean now. Thank you!
