### ISSUE TITLE
Is the vendor/cache directory with gems being used on subsequent image builds?

### ISSUE THREAD

**Issue by genevieve** [paketo-buildpacks/bundle-install#95]
Hey there 👋 

I am testing the performance of building an image with buildpacks vs using a dockerfile with buildkit enabled.

For a given ruby app:
1. I build the image
2. Bump a gem (puma 4.1 -> 4.3) and run `bundle install`
3. I build the image again

I expect the second build to be fast since all of the other gems are available in the `vendor/cache` directory.

With docker buildkit, this step takes ~2 seconds.
```
 => [stage-0 10/16] RUN --mount=type=cache,uid=1000,gid=1000,target=/app/.cache/gems     --network=none     bundle install --local &&     cp -ar .cache/gems   2.3s
```

With the buildpack, it took a few minutes:
```
2020/10/13 16:25:29.971038 Paketo Bundle Install Buildpack 0.0.59
2020/10/13 16:25:29.971201   Executing build process
    Running 'bundle config path /layers/paketo-buildpacks_bundle-install/gems'
2020/10/13 16:25:30.100074     Running 'bundle config cache_path --parseable'
2020/10/13 16:25:30.218272     Running 'bundle install --local'
2020/10/13 16:28:16.406565       Completed in 2m46.624s
```

Since the app has a `vendor/cache` directory with the gems already available, I expected a rebuild after a single gem change to be faster.

**Comment by sophiewigmore** [comment]
Hey @genevieve!
The buildpack currently reruns `bundle install` with the `--local` flag which should tell it to reuse the `vendor/cache` directory. What app are you using so we can try to reproduce this?

**Comment by sophiewigmore** [comment]
Hey @genevieve! We have cut release v0.1.0 of this buildpack with changes that should address this issue. Would you be able to check it out some time and verify that this feature works as you were expecting?

**Comment by genevieve** [comment]
Confirming this works! Changed a gem and it took 3 extra seconds instead of the previous ~3 minutes 👍 
Thank you!

**Comment by sophiewigmore** [comment]
@genevieve great, thanks!
